pipeline:
  build:
    image: plugins/kaniko
    settings:
      repo: harbor.codemowers.eu/${CI_REPO}
      tags: latest
      registry: harbor.codemowers.eu
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: main
